import { formatCurrency, formatDate } from "@/lib/utils";

export function renderIncomeStatementHTML(data: any): string {
  return `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="utf-8">
      <title>Income Statement (P&L)</title>
      <style>
        body { font-family: Arial, sans-serif; padding: 40px; max-width: 800px; margin: 0 auto; }
        h1 { color: #1f2937; border-bottom: 2px solid #3b82f6; padding-bottom: 10px; }
        .header { margin-bottom: 30px; }
        .period { color: #6b7280; }
        table { width: 100%; border-collapse: collapse; margin: 20px 0; }
        th, td { padding: 12px; text-align: left; border-bottom: 1px solid #e5e7eb; }
        th { background-color: #f9fafb; font-weight: 600; }
        .amount { text-align: right; font-family: 'Courier New', monospace; }
        .section-title { font-weight: 600; background-color: #f3f4f6; }
        .total-row { font-weight: 600; border-top: 2px solid #374151; }
        .net-income { background-color: ${data.netIncome >= 0 ? '#d1fae5' : '#fee2e2'}; font-size: 1.1em; }
        .footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #e5e7eb; color: #6b7280; font-size: 0.9em; }
      </style>
    </head>
    <body>
      <div class="header">
        <h1>Income Statement (P&L)</h1>
        <p class="period">Period: ${formatDate(new Date(data.startDate))} - ${formatDate(new Date(data.endDate))}</p>
      </div>

      <h2>Revenue</h2>
      <table>
        <thead>
          <tr>
            <th>Category</th>
            <th class="amount">Amount</th>
          </tr>
        </thead>
        <tbody>
          ${data.revenue.categories.map((cat: any) => `
            <tr>
              <td>${cat.category}</td>
              <td class="amount">${formatCurrency(cat.amount)}</td>
            </tr>
          `).join('')}
          <tr class="total-row">
            <td>Total Revenue</td>
            <td class="amount">${formatCurrency(data.revenue.total)}</td>
          </tr>
        </tbody>
      </table>

      <h2>Expenses</h2>
      <table>
        <thead>
          <tr>
            <th>Category</th>
            <th class="amount">Amount</th>
          </tr>
        </thead>
        <tbody>
          ${data.expenses.categories.map((cat: any) => `
            <tr>
              <td>${cat.category}</td>
              <td class="amount">${formatCurrency(cat.amount)}</td>
            </tr>
          `).join('')}
          <tr class="total-row">
            <td>Total Expenses</td>
            <td class="amount">${formatCurrency(data.expenses.total)}</td>
          </tr>
        </tbody>
      </table>

      <h2>Summary</h2>
      <table>
        <tbody>
          <tr>
            <td>Total Revenue</td>
            <td class="amount">${formatCurrency(data.revenue.total)}</td>
          </tr>
          <tr>
            <td>Total Expenses</td>
            <td class="amount">${formatCurrency(data.expenses.total)}</td>
          </tr>
          <tr class="total-row net-income">
            <td>Net Income</td>
            <td class="amount">${formatCurrency(data.netIncome)}</td>
          </tr>
          <tr>
            <td>Profit Margin</td>
            <td class="amount">${data.profitMargin.toFixed(2)}%</td>
          </tr>
        </tbody>
      </table>

      <div class="footer">
        <p>Generated by Pashoot Reports on ${new Date().toLocaleString()}</p>
      </div>
    </body>
    </html>
  `;
}
