import { Resend } from "resend";

function getResend() {
  return new Resend(process.env.RESEND_API_KEY);
}

export async function sendReportEmail(
  to: string,
  reportName: string,
  reportHtml: string
) {
  try {
    const resend = getResend();
    const { data, error } = await resend.emails.send({
      from: "Pashoot Reports <reports@pashootreports.com>",
      to: [to],
      subject: `Your ${reportName} is ready`,
      html: `
        <h1>Your Report is Ready</h1>
        <p>Your ${reportName} has been generated and is attached below.</p>
        <hr />
        ${reportHtml}
        <hr />
        <p style="color: #666; font-size: 14px;">
          Generated by <a href="${process.env.NEXTAUTH_URL}">Pashoot Reports</a>
        </p>
      `,
    });

    if (error) {
      throw new Error(`Failed to send email: ${error.message}`);
    }

    return { success: true, messageId: data?.id };
  } catch (error) {
    console.error("Email send error:", error);
    throw error;
  }
}

export async function sendWelcomeEmail(to: string, name: string) {
  try {
    const resend = getResend();
    const { data, error } = await resend.emails.send({
      from: "Pashoot Reports <hello@pashootreports.com>",
      to: [to],
      subject: "Welcome to Pashoot Reports!",
      html: `
        <h1>Welcome to Pashoot Reports, ${name}!</h1>
        <p>Thank you for signing up. You're now on your 14-day free trial.</p>
        <h2>Next Steps:</h2>
        <ol>
          <li>Connect your data sources (Wave, Stripe, Xero, etc.)</li>
          <li>Generate your first financial report</li>
          <li>Try the AI chat to ask questions about your finances</li>
        </ol>
        <p>
          <a href="${process.env.NEXTAUTH_URL}/dashboard" style="background: #3b82f6; color: white; padding: 12px 24px; text-decoration: none; border-radius: 6px; display: inline-block;">
            Go to Dashboard
          </a>
        </p>
        <p style="color: #666; margin-top: 40px;">
          Need help? Reply to this email or visit our support center.
        </p>
      `,
    });

    if (error) {
      throw new Error(`Failed to send welcome email: ${error.message}`);
    }

    return { success: true, messageId: data?.id };
  } catch (error) {
    console.error("Welcome email error:", error);
    // Don't throw - welcome email is not critical
    return { success: false, error };
  }
}
