import { generateIncomeStatement } from "./generators/income-statement";
import { generateRevenueBreakdown } from "./generators/revenue-breakdown";
import { generateExpenseByCategory } from "./generators/expense-by-category";
import { generateContractor1099Report } from "./generators/contractor-1099";
import { generateStripeReconciliation } from "./generators/stripe-reconciliation";
import { renderIncomeStatementHTML } from "./templates/income-statement";
import { ReportRequest, ReportData } from "./types";

type ReportGenerator = (request: ReportRequest) => Promise<ReportData>;
type ReportRenderer = (data: ReportData) => string;

interface ReportDefinition {
  generator: ReportGenerator;
  renderer: ReportRenderer;
  name: string;
  description: string;
}

export const reportRegistry: Record<string, ReportDefinition> = {
  income_statement: {
    generator: generateIncomeStatement,
    renderer: renderIncomeStatementHTML,
    name: "Income Statement (P&L)",
    description: "Revenue and expenses breakdown with net income",
  },
  revenue_breakdown: {
    generator: generateRevenueBreakdown,
    renderer: (data) => renderGenericReport(data),
    name: "Revenue Breakdown",
    description: "Revenue by category, source, and time period",
  },
  expense_by_category: {
    generator: generateExpenseByCategory,
    renderer: (data) => renderGenericReport(data),
    name: "Expense Report by Category",
    description: "Expenses categorized and analyzed",
  },
  contractor_1099: {
    generator: generateContractor1099Report,
    renderer: (data) => renderGenericReport(data),
    name: "1099 Contractor Report",
    description: "Contractor payments for tax reporting",
  },
  stripe_reconciliation: {
    generator: generateStripeReconciliation,
    renderer: (data) => renderGenericReport(data),
    name: "Stripe Reconciliation",
    description: "Stripe revenue vs accounting reconciliation",
  },
};

// Generic renderer for reports that don't have custom templates
function renderGenericReport(data: any): string {
  return `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="utf-8">
      <title>${data.reportType}</title>
      <style>
        body { font-family: Arial, sans-serif; padding: 40px; max-width: 900px; margin: 0 auto; }
        h1 { color: #1f2937; border-bottom: 2px solid #3b82f6; padding-bottom: 10px; }
        h2 { color: #374151; margin-top: 30px; }
        .header { margin-bottom: 30px; }
        .period { color: #6b7280; }
        pre { background: #f9fafb; padding: 20px; border-radius: 8px; overflow-x: auto; }
        .footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #e5e7eb; color: #6b7280; font-size: 0.9em; }
      </style>
    </head>
    <body>
      <div class="header">
        <h1>${data.reportType}</h1>
        <p class="period">Period: ${data.startDate?.split('T')[0]} - ${data.endDate?.split('T')[0]}</p>
      </div>

      <h2>Report Data</h2>
      <pre>${JSON.stringify(data, null, 2)}</pre>

      <div class="footer">
        <p>Generated by Pashoot Reports on ${new Date().toLocaleString()}</p>
        <p>Custom template coming soon for this report type.</p>
      </div>
    </body>
    </html>
  `;
}

export function getReportDefinition(reportType: string): ReportDefinition | null {
  return reportRegistry[reportType] || null;
}
